language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t mohamedElsonny/docker-react -f Dockerfile.dev .

script:
  - docker run mohamedElsonny/docker-react yarn test -- --coverage